SELECT 
	A.cidchaves AS 'UKEY_OP', C.cidchaves AS 'UKEY_ITEM', A.EMPDOPNUMS AS 'CHAVE_MAE',C.dtalts AS 'ENTRADA',A.NOTAS AS 'NUM_NF',
	C.opers AS 'TIPO_MOV', A.DOPES AS 'OPERACAO',A.NUMES AS 'NUM_OPS',E.DGRUS AS 'GRP_PRODUTO',C.CPROS AS 'COD_PRODUTO',
	C.DPROS AS 'DESC_PRODUTO',C.QTDS AS 'QTD',C.QTBAIXAS AS 'QTD BAIXADA',C.UNITS AS 'VL_UNITARIO',
	C.CUNIS AS 'UNIDADE', J.rclis AS 'DESTINO', F.RCLIS AS 'ORIGEM', A.obses AS 'OBSERVAÇÃO'
FROM SIGMVCAB A (NOLOCK)
LEFT JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
LEFT JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
LEFT JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
LEFT JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
LEFT JOIN SIGCDCLI F (NOLOCK) ON A.CONTAOS=F.ICLIS
LEFT JOIN SIGCDCLI J (NOLOCK) ON A.contads=J.ICLIS
LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('CANCELA NF RET IND','CANCELA NF VENDA','CANCELAMENTO NF','NF ENT INDUSTRIA','NF PURIFICACAO','NF RET PURIFICAÇÃO',
	'NF RET REM INS N IND','NF RET REMESSA IND.', 'RESUMO ENT MP', 'RESUMO ENT MP.', 'RESUMO ENT MP TOTAL','RET INSUMOS NÃO IND,',
	'RET_INSUMOS_IND','PRE NF COMPRA PEDRA ','PRE NF COMP MP TOTAL','PRE NF COMPRA MP',  'NF COMPRA MP','NF COMPRA MP.')
	--, 'PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN')
	--,'NF COMPRA MP.','NF ENT INDUST ANL','CANCELA NF COMP PEDR','RESUMO ENT MP TOTAL',
	AND C.citem2 = 0
	AND C.opers = 'E'
	AND C.dtalts >'2017-12-01'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL)
	AND (C.cpros = 'OFI' OR C.cpros = 'AU750')
ORDER BY C.dtalts DESC, A.DOPES ASC