SELECT 
CASE 
	WHEN A.CHKSUBN =0 AND A.DOPES IN  ('PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA')  THEN 'PEDIDO PENDENTE' 
	WHEN A.CHKSUBN =1 AND A.DOPES IN  ('PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA')  THEN 'PEDIDO BAIXADO' 
	WHEN A.DOPES IN  ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN') AND A.ULTGRVS <>''   THEN 'PEDIDO BAIXADO'
	WHEN A.DOPES IN  ('REQUISICAO COMPRA') AND A.ULTGRVS <>''   THEN 'PEDIDO BAIXADO' 
	WHEN A.DOPES NOT IN  ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA') THEN '' 
	ELSE 'PEDIDO BAIXADO'
	END AS 'STATUS', 
	A.DATAS AS 'DT_PEDIDO',A.NOTAS AS 'NUMERO_NOTA',
    A.DOPES AS 'OPERACAO',A.NUMES AS 'NUMERO_OPERACAO',I.dopes AS 'OP_FINAN', I.numes AS 'NUM_OP_FINAN',C.QTDS AS 'QTD',
    C.QTBAIXAS AS 'QTD BAIXADA',C.UNITS AS 'VL_UNITARIO', C.cpros AS 'CÓDIGO', C.dpros AS 'DESCRIÇÃO',
    C.MOEDAS AS 'MOEDA', C.CUNIS AS 'UNIDADE',F.RCLIS AS 'FORNECEDOR'
FROM SIGMVCAB A
INNER JOIN SIGCDOPE B ON A.DOPES=B.DOPES
INNER JOIN SIGMVITN C ON A.EMPDOPNUMS=C.EMPDOPNUMS
INNER JOIN SIGCDPRO D ON C.CPROS=D.CPROS
INNER JOIN SIGCDGRP E ON D.CGRUS=E.cgrus
LEFT OUTER JOIN SIGCDCLI F ON A.CONTAOS=F.ICLIS
LEFT OUTER JOIN  SIGPRNFE G WITH(NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS
LEFT OUTER JOIN  SIGOPPIC H WITH(NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS) --ADD EM 26062019 PARA TRAZER NUMERO SUFIXO OP
INNER JOIN SigMvCab I (NOLOCK) ON A.empdopnums = I.empdncrds
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COM MP TOTAL.','PRE NF COMPRA MP','PRE NF COM MP TOTAL')  
AND A.DATAS >'2019-01-01' AND E.DGRUS = 'BRILHANTES'
ORDER BY A.DATAS