SELECT A.emps + A.notas AS 'CHAVE', A.EMPDOPNUMS AS 'CHAVE_MAE', A.emps AS 'EMPRESA', A.DATAS AS 'DT_PEDIDO',
	A.dtalts AS 'DT_ENTREGA', A.PRAZOENTS AS 'PRAZO_ENTREGA',
	A.NOTAS AS 'NUM_NF', C.opers AS 'TIPO_MOV', A.DOPES AS 'OPERACAO',A.NUMES AS 'NUM_OPERACAO',E.DGRUS AS 'GRP_PRODUTO',
	C.CPROS AS 'COD_PRODUTO', C.DPROS AS 'DESC_PRODUTO',C.QTDS AS 'QTD',C.QTBAIXAS AS 'QTD BAIXADA',
	C.UNITS AS 'VL_UNITARIO', C.valipis AS 'IPI',	C.MOEDAS,C.CUNIS AS 'UNIDADE', C.CFOPS AS 'CFOP',
	J.rclis AS 'CLIENTE', F.RCLIS AS 'FORNECEDOR', A.NOPS AS 'NUM_OP',H.nops AS 'SUFIXO', A.obses AS 'OBSERV플O',
	G.stats AS 'VALIDA_STATUS', DATEFROMPARTS(YEAR(A.datas),MONTH(A.datas), 1) AS 'DATA_REF', A.mascnum, K.nops, C.QTDS*C.UNITS + C.valipis AS 'VALOR'
FROM SIGMVCAB A (NOLOCK)
LEFT JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
LEFT JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
LEFT JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
LEFT JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
LEFT JOIN SIGCDCLI F (NOLOCK) ON A.contaos=F.ICLIS
LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
LEFT JOIN SIGOPPIC H (NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS)
LEFT JOIN SIGCDCLI J (NOLOCK) ON A.contads=J.ICLIS
LEFT JOIN SigMvItn M (NOLOCK) ON C.codbarras = M.codbarras AND C.cpros = M.cpros AND M.dopes = 'FINALIZA NACIONAL'
LEFT JOIN SigMvCab N (NOLOCK) ON M.empdopnums = N.empdopnums
LEFT JOIN SigPdMvf K (NOLOCK) ON REPLACE(N.empdncrds, ' ','') = REPLACE(K.empdnps, ' ', '')
LEFT JOIN SigOpPic L (NOLOCK) ON L.nops = K.nops AND M.codbarras = L.codbarras
WHERE A.DOPES IN ('NF RET INDUSTRIALIZA', 'NF VENDA', 'NF VENDA PILOTO', 'DV ASS. TEC. C.CUSTO', 'ENVIO ROMANEIO',
			'NF DEVOLU플O COMPRA', 'NF DEVOLU플O COMPRA.', 'ADIANTA MP FINANC', 'CANCELA NF COMP PEDR', 'DEV RESUMO ENT PEDRA',
			'NF RET PURIFICA플O', 'NF ENT INDUSTRIA')
	AND C.citem2 = 0
	--AND A.DATAS >='2020-06-01'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL)
	--AND A.notas = '006593'
	AND L.numps = 6488
ORDER BY A.dtalts DESC, A.DOPES ASC, A.datas ASC, A.notas ASC