USE DB_RELATORIOS
GO

DROP TABLE TMPSIGPRNFE
GO

--INSERINDO EMPDOPNUMS+STATUS DA NOTA ADICIONADO EM 24052019
select DISTINCT EMPDOPNUMS,STATS,IDS,NOTAS,USUARS INTO TMPSIGPRNFE from DB_ORF.DBO.SIGPRNFE where stats <>'' 
go

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME='Operacoes')
DROP TABLE Operacoes
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME='Operacoes_Historico')
DROP TABLE Operacoes_Historico
GO
--14683
SELECT 
CASE 
	WHEN A.CHKSUBN =0 AND A.DOPES IN  ('PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA')  THEN 'PEDIDO PENDENTE' 
	WHEN A.CHKSUBN =1 AND A.DOPES IN  ('PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA')  THEN 'PEDIDO BAIXADO' 
	WHEN A.DOPES IN  ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN') AND ULTGRVS <>''   THEN 'PEDIDO BAIXADO'
	WHEN A.DOPES IN  ('REQUISICAO COMPRA') AND ULTGRVS <>''   THEN 'PEDIDO BAIXADO' 
	WHEN A.DOPES NOT IN  ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA') THEN '' 
	ELSE 'PEDIDO BAIXADO'
	END AS 'STATUS'
,a.EMPDOPNUMS AS 'CHAVE_MAE',A.DATAS AS 'DT_PEDIDO',A.PRAZOENTS AS 'DT_ENTREGA',A.NOTAS AS 'NUMERO_NOTA',A.DOPES AS 'OPERACAO',A.NUMES AS 'NUMERO_OPERACAO',E.DGRUS AS 'GRP_PRODUTO',C.CPROS AS 'COD_PRODUTO',C.DPROS AS 'DESC_PRODUTO',C.QTDS AS 'QTD',C.QTBAIXAS AS 'QTD BAIXADA',C.UNITS AS 'VL_UNITARIO',C.MOEDAS,C.CUNIS AS 'UNIDADE',C.CFOPS AS 'CFOP',C.SITTRICMS AS 'COD_ICMS',F.RCLIS AS 'FORNECEDOR',A.NOPS AS 'NUM_OP',H.nops AS 'SUFIXO'
,CASE WHEN  EXISTS (SELECT EMPDOPNUMS FROM TMPSIGPRNFE) THEN G.STATS ELSE '' END AS 'STATUS NF'
INTO Operacoes
FROM DB_ORF.DBO.SIGMVCAB A
INNER JOIN DB_ORF.DBO.SIGCDOPE B ON A.DOPES=B.DOPES
INNER JOIN DB_ORF.DBO.SIGMVITN C ON A.EMPDOPNUMS=C.EMPDOPNUMS
INNER JOIN DB_ORF.DBO.SIGCDPRO D ON C.CPROS=D.CPROS
INNER JOIN DB_ORF.DBO.SIGCDGRP E ON D.CGRUS=E.cgrus
LEFT OUTER JOIN DB_ORF.DBO.SIGCDCLI F ON A.CONTAOS=F.ICLIS
LEFT OUTER JOIN  TMPSIGPRNFE G WITH(NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS
LEFT OUTER JOIN  DB_ORF.DBO.SIGOPPIC H WITH(NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS) --ADD EM 26062019 PARA TRAZER NUMERO SUFIXO OP
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('REQUISICAO COMPRA','PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMPRA PEDRA','CANCELAMENTO NF','DEVOLU플O DE VENDAS','NF COMPRA DIVERSAS','NF COMPRA MP','NF COMPRA PEDRA','NF DEVOLUCAO VENDA','NF RET REMESSA IND.','PRE NF COM MP TOTAL.',
'PRE NF COMPRA MP','RESUMO ENT MP','RESUMO ENT MP TOTAL','DEVOLU플O DE VENDAS','NF DEV MERC IND','NF DEVOLUCAO VENDA','NF ENTRADA DIVERSAS','NF OUTRAS SAIDAS DI.','NF OUTRAS SAIDAS DIV','NF SAIDA DIVERSAS','NF SIMPLES FATURA','NF SIMPLES FATURA.','NF VENDA','NF VENDA ENT FUTURA','NF VENDA PILOTO','SIMPLES_FATURAMENTO')  
AND A.DATAS >'2018-01-01'
--AND A.EMPDOPNUMS='ORFNF COMPRA MP           567'
ORDER BY A.DATAS
GO


--hISTorico operacoes SEMPRE ANDAM JUNTO COM OS DOPES DAS OPERACOES ACIMA 
SELECT DATAS AS 'DATA_BAIXA',EMPBS AS 'EMPRESA_MAE',DOPEBS AS 'OPERACAO_MAE',NUMEBS AS 'NUM_MAE',EMPS AS 'EMPESA_BAIXA',DOPES AS 'OPERACAO_BAIXA',NUMES AS 'NUM_BAIXA',CITENS,CPROS AS 'COD_PRODUTO',CODTAMS,empdopnumb AS 'CHAVE_MAE',empdopnums AS 'CHAVE_BAIXA' 
INTO Operacoes_Historico
FROM  DB_ORF.DBO.SIGBXEST 
--WHERE  QTDES<>'0.00' and DOPEBS IN ('REQUISICAO COMPRA','PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMPRA PEDRA','CANCELAMENTO NF','DEVOLU플O DE VENDAS','NF COMPRA DIVERSAS','NF COMPRA MP','NF COMPRA PEDRA','NF DEVOLUCAO VENDA','NF RET REMESSA IND.','PRE NF COM MP TOTAL.',
--'PRE NF COMPRA MP','RESUMO ENT MP','RESUMO ENT MP TOTAL') 
--AND DATAS > '2018-01-01'
WHERE  QTDES<>'0.00' and DOPEBS IN ('REQUISICAO COMPRA','PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMPRA PEDRA','CANCELAMENTO NF','DEVOLU플O DE VENDAS','NF COMPRA DIVERSAS','NF COMPRA MP','NF COMPRA PEDRA','NF DEVOLUCAO VENDA','NF RET REMESSA IND.','PRE NF COM MP TOTAL.',
'PRE NF COMPRA MP','RESUMO ENT MP','RESUMO ENT MP TOTAL','DEVOLU플O DE VENDAS','NF DEV MERC IND','NF DEVOLUCAO VENDA','NF ENTRADA DIVERSAS','NF OUTRAS SAIDAS DI.','NF OUTRAS SAIDAS DIV','NF SAIDA DIVERSAS','NF SIMPLES FATURA','NF SIMPLES FATURA.','NF VENDA','NF VENDA ENT FUTURA','NF VENDA PILOTO','SIMPLES_FATURAMENTO')  
AND DATAS > '2018-01-01'
