SELECT
	CAST(A.datas AS DATE) AS 'ENTRADA', F.rclis AS 'FORNECEDOR', A.NOTAS AS 'BOLETA',E.DGRUS AS 'GRP_PRODUTO', 
	A.NUMES AS 'NUM_OP_ESTOQ', A.DOPES AS 'OP_ESTOQ', I.numes AS 'NUM_OP_FINAN', I.dopes AS 'OP_FINAN',
	SUM(C.qtds) AS 'KILATAGEM', SUM(C.units) AS 'QTD_TOTAL', SUM(C.qtds*C.units) AS 'VL_TOTAL',
	A.valinis AS 'VL_R$', I.empdopnums, A.CHKSUBN 'BAIXA_ESTOQ', I.chkbxparcs 'BAIXA_FINAN'
FROM SIGMVCAB A (NOLOCK)
INNER JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
INNER JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
INNER JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
INNER JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
LEFT OUTER JOIN SIGCDCLI F (NOLOCK) ON A.CONTAOS=F.ICLIS
LEFT OUTER JOIN  SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS
LEFT OUTER JOIN  SIGOPPIC H (NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS) --ADD EM 26062019 PARA TRAZER NUMERO SUFIXO OP
INNER JOIN SigMvCab I (NOLOCK) ON A.empdopnums = I.empdncrds
WHERE A.dopes IN ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMP MP TOTAL','PRE NF COM MP TOTAL.','PRE NF COMPRA MP')
	AND A.DATAS >'2019-01-01' AND E.DGRUS = 'BRILHANTES'
	--AND A.numes = 1395
GROUP BY A.NOTAS, E.DGRUS, A.datas, A.DOPES, A.NUMES, A.nops, A.datas, I.dopes, I.numes, A.valinis, I.empdopnums, A.chksubn, I.chkbxparcs, F.rclis
ORDER BY 'ENTRADA' DESC;