SELECT
	A.datas AS 'ENTRADA', F.rclis AS 'FORNECEDOR', A.NOTAS AS 'BOLETA',E.DGRUS AS 'GRP_PRODUTO', 
	A.NUMES AS 'NUM_OP_ESTOQ', A.DOPES AS 'OP_ESTOQ', D.cpros AS 'COD_PEDRA', D.dpros AS 'DESC_PEDRA',
	C.qtds AS 'KILATAGEM', C.pesos AS 'QTD', C.qtds*C.units AS 'VL_TOTAL',
	A.valinis AS 'VL_R$', A.obses 'OBSERVACAO', A.empdopnums as 'EMPDOPNUMS'
FROM SIGMVCAB A (NOLOCK)
INNER JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
INNER JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
INNER JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
INNER JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
LEFT OUTER JOIN SIGCDCLI F (NOLOCK) ON A.CONTAOS=F.ICLIS
WHERE A.dopes IN ('RESUMO ENT MP','RESUMO ENT MP TOTAL','RESUMO ENT MP.','RESUMO ENT PEDRA','RESUMO ENT PEDRA.')
	AND A.DATAS >'2020-01-01' AND E.DGRUS = 'PEDRAS'
ORDER BY 'ENTRADA' DESC;