--Lista de NFs
SELECT 
	A.EMPDOPNUMS AS 'CHAVE_MAE', I.emis AS 'DT_EMISSAO', A.PRAZOENTS AS 'DT_ENTRADA',A.NOTAS AS 'NUM_NF',
	A.DOPES AS 'OPERACAO',A.NUMES AS 'NUM_OPS', A.emps AS 'EMPRESA', A.NOPS AS 'NUM_OP', G.stats AS 'VALIDA_STATUS',
	DATEFROMPARTS(YEAR(I.emis),MONTH(I.emis), 1) AS 'MES_REF', I.cancelas AS 'NF_CANCELA', I.series AS 'SERIES',
	CASE 
		WHEN A.dopes IN ('ENVIO ROMANEIO', 'NF VENDA', 'NF VENDA PILOTO', 'NF RET INDUSTRIALIZA',
		'NF DEVOLU플O COMPRA.', 'DV ASS. TEC. C.CUSTO', 'NF OUTRAS SAIDAS DI.', 'NF RET MERC IND     ',
		'NF SAIDA DIVERSAS   ', 'NF COMPLEMENTAR     ', 'NF PURIFICACAO      ', 'NF REMESSA CONSIGNAD',
		'DEV RESUMO ENT PEDRA', 'RETORNO CONSERTO HS ', 'NF SAIDA DEMONSTRA  ') THEN J.rclis
		ELSE F.rclis
	END AS 'COD_EMPRESA',
	CASE 
		WHEN A.dopes IN ('ENVIO ROMANEIO', 'NF VENDA', 'NF VENDA PILOTO', 'NF RET INDUSTRIALIZA',
		'NF DEVOLU플O COMPRA.', 'DV ASS. TEC. C.CUSTO', 'NF OUTRAS SAIDAS DI.', 'NF RET MERC IND     ',
		'NF SAIDA DIVERSAS   ', 'NF COMPLEMENTAR     ', 'NF PURIFICACAO      ', 'NF REMESSA CONSIGNAD',
		'DEV RESUMO ENT PEDRA', 'RETORNO CONSERTO HS ', 'NF SAIDA DEMONSTRA  ') THEN J.iclis
		ELSE F.iclis
	END AS 'EMPRESA',
	CASE	
		WHEN A.DOPES IN ('NF RET INDUSTRIALIZA', 'NF VENDA', 'NF VENDA PILOTO', 'DV ASS. TEC. C.CUSTO',
			'NF DEVOLU플O COMPRA', 'NF DEVOLU플O COMPRA.', 'ADIANTA MP FINANC', 'DEV RESUMO ENT PEDRA',
			'NF RET PURIFICA플O', 'NF ENT INDUSTRIA') THEN 'RECEBIMENTO'
		ELSE '' 
	END AS 'CATEGORIA_NF', CAST(A.obses AS varchar(max)) AS 'OBSERV플O'
FROM SIGMVCAB A (NOLOCK)
LEFT JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
LEFT JOIN SIGCDCLI F (NOLOCK) ON A.CONTAOS=F.ICLIS
LEFT JOIN SIGCDCLI J (NOLOCK) ON A.contads=J.ICLIS
LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I 
																		WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
LEFT JOIN SigMvNfi I (NOLOCK) ON I.empdopnums = A.empdopnums
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('ADIANTA MP FINANC','CANCELA NF COMP PEDR','CANCELA NF RET IND','CANCELA NF VENDA','CANCELAMENTO NF',
	'DEV RESUMO ENT PEDRA','DEVOLU플O DE VENDAS','DV ASS. TEC. C.CUSTO','ENTRADA CONSERTO HS','ENVIO ROMANEIO','INUTILIZACAO',
	'INUTILIZACAO','NF COBRANCA RET IND','NF COMPLEMENTAR','NF COMPRA DIVERSAS','NF COMPRA MP','NF COMPRA MP.','NF COMPRA PEDRA',
	'NF CONSIGNADO','NF DEV CONSIGNADO','NF DEV MERC IND','NF DEV OUTRAS ENT','NF DEVOLU플O COMPRA','NF DEVOLU플O COMPRA.',
	'NF DEVOLUCAO VENDA','NF ENT DEMONSTRA플O','NF ENT INDUST ANL','NF ENT INDUSTRIA','NF ENTRADA DIVERSAS','NF INDUSTRIALIZACAO',
	'NF OUTRAS ENTRADAS','NF OUTRAS SAIDAS DI.','NF OUTRAS SAIDAS DIV','NF PURIFICACAO','NF REMESSA CONSIGNAD','NF REMESSA IND',
	'NF RET INDUSTRIA','NF RET INDUSTRIALIZA','NF RET MERC IND','NF RET PURIFICA플O','NF RET REM INS N IND','NF RET REMESSA IND.',
	'NF RETORNO CONSIGNAD','NF SAIDA DEMONSTRA','NF SAIDA DIVERSAS','NF VENDA','NF VENDA PILOTO','NF VENDA PILOTO',
	'RESUMO ENT MP','RESUMO ENT MP TOTAL','RET INSUMOS N홒 IND,','RET INSUMOS NAO IND.','RET_INSUMOS_IND',
	'RETORNO CONSERTO HS')
--WHERE (C.CFOPS NOT LIKE '' OR C.CFOPS IN ('CANCELA NF COMP PEDR', 'CANCELAMENTO NF', 'DEV RESUMO ENT PEDRA', 'DEVOLU플O DE VENDAS',
--			'DV ASS. TEC. C.CUSTO', 'ENVIO ROMANEIO', 'NF ENT DEMONSTRA플O', 'RESUMO ENT MP', 'RESUMO ENT MP TOTAL'))
	AND A.DATAS >'2018-01-01'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL)
	--AND (A.notas = '000179' OR A.notas = '000180') 
	--AND A.dopes = 'NF COMPRA MP'
	--AND G.datas > '2019-10-01'