SELECT 
	A.cidchaves AS 'UKEY_OP', C.cidchaves AS 'UKEY_ITEM', A.EMPDOPNUMS AS 'CHAVE_MAE',C.dtalts AS 'ENTRADA',
	A.NOTAS AS 'NUM_NF', C.opers AS 'TIPO_MOV', A.DOPES AS 'OPERACAO',A.NUMES AS 'NUM_OPS',E.DGRUS AS 'GRP_PRODUTO',
	C.CPROS AS 'COD_PRODUTO', C.DPROS AS 'DESC_PRODUTO',C.QTDS AS 'QTD',C.QTBAIXAS AS 'QTD BAIXADA',
	C.UNITS AS 'VL_UNITARIO', C.CUNIS AS 'UNIDADE', C.qtds, C.cunis, C.totas, C.moevs, A.valinis, A.valos, J.rclis AS 'DESTINO',F.RCLIS AS 'ORIGEM'
FROM SIGMVCAB A (NOLOCK)
	LEFT JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
	LEFT JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
	LEFT JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
	LEFT JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
	LEFT JOIN SIGCDCLI F (NOLOCK) ON A.CONTAOS=F.ICLIS
	LEFT JOIN SIGCDCLI J (NOLOCK) ON A.contads=J.ICLIS
	LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
	LEFT JOIN SIGOPPIC H (NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS) --ADD EM 26062019 PARA TRAZER NUMERO SUFIXO OP
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('CANCELA NF RET IND','CANCELA NF VENDA','CANCELAMENTO NF','NF COMPLEMENTAR',
	'NF ENT INSUT ANL', 'NF RET INDUTRIALIZA','NF RET MERC IND', 'NF RET MERC IND', 'NF SAIDA DIVERSAS',
	'NF ENT INDUSTRIA','NF PURIFICACAO','PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA',
	'NF RET PURIFICAÇÃO','NF RET REM INS N IND','NF RET REMESSA IND.', 'RESUMO ENT MP', 'RESUMO ENT MP.',
	'RET INSUMOS NÃO IND,','RET_INSUMOS_IND')
	-- 'NF COMPRA MP','NF COMPRA MP.','NF ENT INDUST ANL','CANCELA NF COMP PEDR','RESUMO ENT MP TOTAL',
	AND C.citem2 = 0
	--AND C.dtalts > GETDATE() - 90 --'2019-01-01'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL)
	--AND C.dpros LIKE 'AGUA MARINHA %'
ORDER BY C.dtalts DESC, A.DOPES ASC