SELECT K.dopps AS 'OPERACAO', K.empdnps AS 'CHAVE FINALIZAÇÃO', N.dopes AS 'OPERAÇÃO FINAN', N.empdopnums AS 'CHAVE FINALIZAÇÃO FINAN', M.codbarras AS 'Cód.Barras'
	A.EMPDOPNUMS AS 'CHAVE_NF', DATEFROMPARTS(YEAR(A.dtalts),MONTH(A.dtalts), DAY(A.dtalts)) AS 'DT_EMISSÃO', A.datas, A.DOPES AS 'OPERACAO',A.NOTAS AS 'NUM_NF', C.CFOPS AS 'CFOP', 
	A.emps AS 'EMPRESA',  J.rclis AS 'CLIENTE', K.nops AS 'NUM_OP', E.DGRUS AS 'GRP_PRODUTO', C.CPROS AS 'COD_PRODUTO', C.DPROS AS 'DESC_PRODUTO',C.QTDS AS 'QTD',
	A.obses AS 'OBSERVÇÃO', G.stats AS 'VALIDA_STATUS', DATEFROMPARTS(YEAR(K.datars),MONTH(K.datars), 1) AS 'MES_REF_FINAL', C.QTDS*C.UNITS + C.valipis AS 'VALOR',
	K.datars AS 'DATA FINALIZAÇÃO'
FROM SIGMVCAB A (NOLOCK)
	LEFT JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
	LEFT JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
	LEFT JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
	LEFT JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
	LEFT JOIN SIGCDCLI F (NOLOCK) ON A.contaos=F.ICLIS
	LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
	LEFT JOIN SIGOPPIC H (NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS)
	LEFT JOIN SIGCDCLI J (NOLOCK) ON A.contads=J.ICLIS
	LEFT JOIN SigMvItn M (NOLOCK) ON C.codbarras = M.codbarras AND C.cpros = M.cpros AND M.dopes = 'FINALIZA NACIONAL'
	LEFT JOIN SigMvCab N (NOLOCK) ON M.empdopnums = N.empdopnums
	LEFT JOIN SigPdMvf K (NOLOCK) ON REPLACE(N.empdncrds, ' ','') = REPLACE(K.empdnps, ' ', '')
	LEFT JOIN SigOpPic L (NOLOCK) ON L.nops = K.nops AND M.codbarras = L.codbarras
WHERE A.DOPES IN ('NF RET INDUSTRIALIZA', 'NF VENDA', 'NF VENDA PILOTO', 'ENVIO ROMANEIO','NF RET PURIFICAÇÃO')
	--'DV ASS. TEC. C.CUSTO','ADIANTA MP FINANC', 'CANCELA NF COMP PEDR', 'DEV RESUMO ENT PEDRA','NF DEVOLUÇÃO COMPRA', 'NF DEVOLUÇÃO COMPRA.', 'NF ENT INDUSTRIA' 
	AND M.dopes NOT LIKE ''
	AND C.citem2 = 0
	AND A.DATAS >='01-01-2020'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL OR G.stats = '   ')
	AND K.dopps NOT LIKE ''
	--AND A.notas = '006593'
	--AND L.numps = 6488
ORDER BY A.dtalts DESC, A.DOPES ASC, A.datas ASC, A.notas ASC