--/ Consulta para alimentar o futuro Controle de Compras, objetivo é
--/ listar Pedidos, Itens do Pedido, OPs, Itens da OP e as requisições de compra relacionadas!
SELECT A.datas AS 'DATA_ENTRADA', A.mascnum AS 'PEDIDO', H.dopes AS 'TIPO_PEDIDO', A.nops AS 'OP_MAE', H.nops AS 'OP',
	(SELECT DISTINCT J.cpros
		FROM SigMvCab (NOLOCK) AS I
			INNER JOIN SigMvItn (NOLOCK) AS J ON I.EMPDOPNUMS = J.EMPDOPNUMS
			INNER JOIN SigOpPic (NOLOCK) AS K ON J.cpros = K.cpros
			WHERE H.nops = K.nops) AS 'COD_PRODUTO',
	H.dpros AS 'DESCRIÇAO', C.qtds AS 'QUANT_TOT', E.DGRUS AS 'GRP_INSUMO', C.CPROS AS 'COD_INSUMO',
	C.DPROS AS 'DESC_INSUMO', C.QTDS AS 'QTD TOTAL', C.QTBAIXAS AS 'QTD BAIXADA',
	C.MOEDAS, C.CUNIS AS 'UNIDADE', C.UNITS AS 'VL_UNITARIO', F.RCLIS AS 'FORNECEDOR',
	CASE
		WHEN A.CHKSUBN =0 AND A.DOPES IN  ('PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA')  THEN 'PEDIDO PENDENTE'
		WHEN A.CHKSUBN =1 AND A.DOPES IN  ('PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA')  THEN 'PEDIDO BAIXADO'
		WHEN A.DOPES IN  ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN') AND ULTGRVS <>''   THEN 'PEDIDO BAIXADO'
		WHEN A.DOPES IN  ('REQUISICAO COMPRA') AND ULTGRVS <>''   THEN 'PEDIDO BAIXADO'
		WHEN A.DOPES NOT IN  ('PRE NF MP TOTAL FINA','PRE NF COMP MP FINAN','PRE NF COMP MP TOTAL','PRE NF COMPRA MP','PRE NF COMPRA PEDRA') THEN ''
		ELSE 'PEDIDO BAIXADO'
	END AS 'STATUS',
	A.NUMES AS 'NUMERO_OPERACAO',
	A.DOPES AS 'OPERAÇÃO',
	CASE
		WHEN EXISTS (SELECT J.EMPDOPNUMS FROM sigprnfe AS J) THEN G.STATS ELSE '' END AS 'STATUS NF'
	FROM SigMvCab AS A (NOLOCK)
	INNER JOIN SigCdOpe AS B (NOLOCK) ON A.DOPES = B.DOPES
	INNER JOIN SigMvItn AS C (NOLOCK) ON A.EMPDOPNUMS = C.EMPDOPNUMS
	INNER JOIN SigCdPro AS D (NOLOCK) ON C.CPROS = D.CPROS
	INNER JOIN SigCdGrp AS E (NOLOCK) ON D.CGRUS = E.cgrus
	LEFT OUTER JOIN SIGCDCLI AS F (NOLOCK) ON A.CONTAOS=F.ICLIS
	LEFT OUTER JOIN sigprnfe AS G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS
	LEFT OUTER JOIN  SigOpPic AS H (NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS) --ADD EM 26062019 PARA TRAZER NUMERO SUFIXO OP
	--WHERE B.tipoops in ('1','9')
	WHERE A.DOPES IN ('REQUISICAO COMPRA')
		AND A.DATAS >'2019-01-01'
		AND C.CPROS NOT LIKE 'AU750'
--		AND C.cidchaves = 'ORF5I014TEHE83007748'
	--AND A.EMPDOPNUMS='ORFNF COMPRA MP           567'
	ORDER BY A.DATAS DESC, A.NOPS ASC, H.nops ASC, 'STATUS' DESC