--Componentes da NF
--VALIDAR SE PODEMOS INCLUIR AS PRÉ-NFs E NFs! Eliminaria a necessidade de Tabela Comp_PreNF_NF_Compra
SELECT A.empdopnums AS 'CHAVE', --SUM(C.QTDS*C.UNITS + C.valipis) AS 'VALOR',
	DATEFROMPARTS(YEAR(A.datas),MONTH(A.datas), 1) AS 'DATA_REF', L.dopes AS 'TIPO_PEDIDO',	L.numes AS 'PEDIDO',
	L.numps AS 'OP_GERAL', H.nops AS 'OP_ITEM', E.DGRUS AS 'GRP_PRODUTO', C.CPROS AS 'COD_PRODUTO', C.DPROS AS 'DESC_PRODUTO',
	C.CFOPS AS 'CFOP', C.QTDS AS 'QTD',C.QTBAIXAS AS 'QTD_BAIXADA', REPLACE(K.empdnps, ' ', '') AS 'FINALIZACAO',
	C.QTDS*C.UNITS AS 'VALOR_TOT_S/_IPI', C.QTDS*C.UNITS + C.valipis AS 'VALOR_TOTAL', C.UNITS AS 'VL_UNITARIO',
	C.valipis AS 'IPI',	C.MOEDAS AS 'MOEDA', C.CUNIS AS 'UNIDADE', C.baseicms AS 'BASE_ICMS', C.icms AS 'ICMS',
	C.aliqicms AS 'ALIQ_ICMS', C.SITTRICMS AS 'COD_ICMS', (C.QTDS*C.UNITS)/(1-0.015) - (C.QTDS*C.UNITS) AS 'VALOR ICMS',
	(C.QTDS*C.UNITS)/(1-0.02) - (C.QTDS*C.UNITS) AS 'VALOR FECP', C.vpis AS 'PIS', C.aliqpis AS 'ALIQ_PIS', C.vcofins AS 'COFINS',
	C.aliqcofs AS 'ALIQ_COFINS', C.bcipis AS 'BASE_IPI', C.valipis AS 'IPI', C.aliqs AS 'ALIQ_IPI', C.cssl AS 'CSSL', C.iss AS 'ISS', H.*
FROM SIGMVCAB A (NOLOCK)
LEFT JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
LEFT JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS	
LEFT JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
LEFT JOIN SigMvItn M (NOLOCK) ON C.codbarras = M.codbarras AND C.cpros = M.cpros AND M.dopes = 'FINALIZA NACIONAL'
LEFT JOIN SigMvCab N (NOLOCK) ON M.empdopnums = N.empdopnums
LEFT JOIN SigPdMvf K (NOLOCK) ON REPLACE(N.empdncrds, ' ','') = REPLACE(K.empdnps, ' ', '')
LEFT JOIN SigOpPic L (NOLOCK) ON L.nops = K.nops AND M.codbarras = L.codbarras
LEFT JOIN SIGOPPIC H (NOLOCK) ON L.numps=H.NUMPS AND C.cpros = H.cpros AND C.codbarras = H.codbarras --LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS)
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('NF RET INDUSTRIALIZA', 'NF VENDA', 'NF VENDA PILOTO', 'DV ASS. TEC. C.CUSTO',
			'NF DEVOLUÇÃO COMPRA', 'NF DEVOLUÇÃO COMPRA.', 'ADIANTA MP FINANC', 'DEV RESUMO ENT PEDRA',
			'NF RET PURIFICAÇÃO', 'NF ENT INDUSTRIA')
	AND C.citem2 = 0
	AND A.datas >='2016-01-01'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL)