SELECT 
	A.EMPDOPNUMS AS 'CHAVE_MAE', I.emis AS 'DT_EMISSAO', A.PRAZOENTS AS 'DT_ENTREGA',A.NOTAS AS 'NUM_NF',C.opers AS 'TIPO_MOV',
	A.DOPES AS 'OPERACAO',A.NUMES AS 'NUM_OPS',E.DGRUS AS 'GRP_PRODUTO',C.CPROS AS 'COD_PRODUTO',
	C.DPROS AS 'DESC_PRODUTO', C.QTDS AS 'QTD', C.QTBAIXAS AS 'QTD BAIXADA', C.UNITS AS 'VL_UNITARIO',
	C.baseicms AS 'BASE_ICMS', C.icms AS 'ICMS', C.aliqicms AS 'ALIQ_ICMS', C.vpis AS 'PIS', C.aliqpis AS 'ALIQ_PIS',
	C.vcofins AS 'COFINS', C.aliqcofs AS 'ALIQ_COFINS', C.bcipis AS 'BASE_IPI', C.valipis AS 'IPI', C.aliqs AS 'ALIQ_IPI',
	C.cssl AS 'CSSL', C.iss AS 'ISS', C.MOEDAS,C.CUNIS AS 'UNIDADE', C.CFOPS AS 'CFOP',C.SITTRICMS AS 'COD_ICMS',
	J.iclis AS 'COD_DESTINO', J.rclis AS 'DESTINO', F.iclis AS 'COD_ORIGEM', F.RCLIS AS 'ORIGEM', A.NOPS AS 'NUM_OP',
	H.nops AS 'SUFIXO', G.stats AS 'VALIDA_STATUS', DATEFROMPARTS(YEAR(I.emis),MONTH(I.emis), 1) AS 'MES_REF',
	I.cancelas AS 'NF_CANCELA', I.series AS 'SERIES', C.QTDS*C.UNITS AS 'VALOR S/ IPI', C.QTDS*C.UNITS + C.valipis AS 'VALOR TOTAL',
	(C.QTDS*C.UNITS)/(1-0.015) - (C.QTDS*C.UNITS) AS 'VALOR ICMS', (C.QTDS*C.UNITS)/(1-0.02) - (C.QTDS*C.UNITS) AS 'VALOR FECP'--, G.stats
FROM SIGMVCAB A (NOLOCK)
	LEFT JOIN SIGCDOPE B (NOLOCK) ON A.DOPES=B.DOPES
	LEFT JOIN SIGMVITN C (NOLOCK) ON A.EMPDOPNUMS=C.EMPDOPNUMS
	LEFT JOIN SIGCDPRO D (NOLOCK) ON C.CPROS=D.CPROS
	LEFT JOIN SIGCDGRP E (NOLOCK) ON D.CGRUS=E.cgrus
	LEFT JOIN SIGCDCLI F (NOLOCK) ON A.CONTAOS=F.ICLIS
	LEFT JOIN SIGCDCLI J (NOLOCK) ON A.contads=J.ICLIS
	LEFT JOIN SIGPRNFE G (NOLOCK) ON A.EMPDOPNUMS=G.EMPDOPNUMS AND G.datas = (SELECT MAX(I.datas) FROM sigprnfe I WHERE A.EMPDOPNUMS=I.EMPDOPNUMS GROUP BY I.empdopnums)
	LEFT JOIN SIGOPPIC H (NOLOCK) ON A.NOPS=H.NUMPS AND LTRIM(CONVERT(NVARCHAR,C.OBS))=CONVERT(NVARCHAR,H.NOPS) --ADD EM 26062019 PARA TRAZER NUMERO SUFIXO OP
	LEFT JOIN SigMvNfi I (NOLOCK) ON I.empdopnums = A.empdopnums
--WHERE B.tipoops in ('1','9') 
WHERE A.DOPES IN ('ADIANTA MP FINANC','CANCELA NF COMP PEDR','CANCELA NF RET IND','CANCELA NF VENDA','CANCELAMENTO NF',
	'DEV RESUMO ENT PEDRA','DEVOLU플O DE VENDAS','DV ASS. TEC. C.CUSTO','ENTRADA CONSERTO HS','ENVIO ROMANEIO','INUTILIZACAO',
	'INUTILIZACAO','NF COBRANCA RET IND','NF COMPLEMENTAR','NF COMPRA DIVERSAS','NF COMPRA MP','NF COMPRA MP.','NF COMPRA PEDRA',
	'NF CONSIGNADO','NF DEV CONSIGNADO','NF DEV MERC IND','NF DEV OUTRAS ENT','NF DEVOLU플O COMPRA','NF DEVOLU플O COMPRA.',
	'NF DEVOLUCAO VENDA','NF ENT DEMONSTRA플O','NF ENT INDUST ANL','NF ENT INDUSTRIA','NF ENTRADA DIVERSAS','NF INDUSTRIALIZACAO',
	'NF OUTRAS ENTRADAS','NF OUTRAS SAIDAS DI.','NF OUTRAS SAIDAS DIV','NF PURIFICACAO','NF REMESSA CONSIGNAD','NF REMESSA IND',
	'NF RET INDUSTRIA','NF RET INDUSTRIALIZA','NF RET MERC IND','NF RET PURIFICA플O','NF RET REM INS N IND','NF RET REMESSA IND.',
	'NF RETORNO CONSIGNAD','NF SAIDA DEMONSTRA','NF SAIDA DIVERSAS','NF VENDA','NF VENDA PILOTO','NF VENDA PILOTO',
	'RESUMO ENT MP','RESUMO ENT MP TOTAL','RET INSUMOS N홒 IND,','RET INSUMOS NAO IND.','RET_INSUMOS_IND',
	'RETORNO CONSERTO HS')
--WHERE (C.CFOPS NOT LIKE '' OR C.CFOPS IN ('CANCELA NF COMP PEDR', 'CANCELAMENTO NF', 'DEV RESUMO ENT PEDRA', 'DEVOLU플O DE VENDAS',
--			'DV ASS. TEC. C.CUSTO', 'ENVIO ROMANEIO', 'NF ENT DEMONSTRA플O', 'RESUMO ENT MP', 'RESUMO ENT MP TOTAL'))
	AND C.citem2 = 0
	AND A.DATAS >'2019-01-01'
	AND (G.stats NOT LIKE '' OR G.stats IS NULL OR G.stats LIKE '   ')
--	AND A.notas IN ('008293', '008262', '008277', '008306')
	--AND (A.notas = '000179' OR A.notas = '000180') 
	--AND A.dopes = 'NF COMPRA MP'
	--AND G.datas > '2019-10-01'
ORDER BY I.emis ASC, A.DOPES ASC, A.datas ASC